### ISSUE TITLE
MKConsoleWindow.m uses a declaration which conflicts with AppKit header, this breaks the build

### ISSUE THREAD

**Issue by barracuda156** [mulle-kybernetik/mkconsole#1]
```
    /Developer/usr/bin/gcc-4.2 -x objective-c -arch ppc -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -Os -mdynamic-no-pic -mtune=G4 -fvisibility=hidden -mmacosx-version-min=10.6 -gdwarf-2 -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/build/MkConsole.build/Deployment/MkConsole.build/MkConsole.hmap -F/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/build/Deployment -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/build/Deployment/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/build/MkConsole.build/Deployment/MkConsole.build/DerivedSources -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/MKConsoleWindow.m -o /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/build/MkConsole.build/Deployment/MkConsole.build/Objects-normal/ppc/MKConsoleWindow.o
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/MKConsoleWindow.m:49: error: expected ‘)’ before ‘NSWindowStyleMask’
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/MKConsoleWindow.m: In function ‘-[MKConsoleWindow initWithContentRect:styleMask:backing:defer:]’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_mkconsole/mkconsole/work/mkconsole-1.14/MKConsoleWindow.m:50: warning: conflicting types for ‘-(id)initWithContentRect:(NSRect)contentRect styleMask:(id)styleMask backing:(NSBackingStoreType)backingType defer:(BOOL)flag’
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:263: warning: previous declaration of ‘-(id)initWithContentRect:(NSRect)contentRect styleMask:(NSUInteger)aStyle backing:(NSBackingStoreType)bufferingType defer:(BOOL)flag’
```

**Comment by znek** [comment]
Which (ancient) version of Xcode do you use? In any case the definition of styleMask being of type `id` is plain wrong, it could have been `int` in ancient times, but never `id`.

However, this specific method implementation uses a proper signature that's valid for quite some API generations.

**Comment by barracuda156** [comment]
It seems that the issue is with one of the arguments. Definition sits in the system header and explicitly differs from the one in the code here. FWIW, if that argument is changed to match the system header, build succeeds.

P. S. Xcode 3.2, but it seems there is no compatibility issues, this code can be built with it.

**Comment by znek** [comment]
The old definition of style mask was `NSUInteger`, that's what your AppKit headers also provide. The conflicting type containing `id` for styleMask is bogus, because your AppKit headers don't define `NSWindowStyleMaskBorderless`, thus it's _assumed_ to be `id` - which it is not. The old name for `NSWindowStyleMaskBorderless` was `NSBorderlessWindowMask`. I can't say precisely which SDK changed definitions.

**Comment by barracuda156** [comment]
@znek Could you suggest an appropriate fix? If it is a matter of one definition, perhaps it can be fixed here in upstream (AvailabilityMacros.h got everything we need for that). If the patch turns out to be too big, at least I can submit a fix to MacPorts.

**Comment by znek** [comment]
I'm reactivating old VMs in order to find the exact point where definitions changed in the SDKs in order to properly guard this with `AvailabilityMacros.h`. This unfortunately takes a while, but it's definitely not big. Something like:
```
// NOTE: can't use version macros when compiling on old platforms
// as these macros are undefined there
#if (__MAC_OS_X_VERSION_MAX_ALLOWED <= 101400)
#define NSWindowStyleMaskBorderless NSBorderlessWindowMask
#define NSWindowStyleMask NSUInteger
#endif
```

Please try this out on your platform, it should work - otherwise, let me know.

**Comment by znek** [comment]
The definition changed as of MacOSX10.12.sdk. The appropriate change is upstreamed with [2ed5412] now. Have fun building for `ppc`. ;-)

**Comment by barracuda156** [comment]
@znek Thank you, that worked!
